/**
 * World capitals — city + country pairs used for location search.
 * Sorted alphabetically by city name.
 */
export interface Capital {
  city: string;
  country: string;
  /** "city, country" display label */
  label: string;
}

const RAW: [string, string][] = [
  ["Abu Dhabi", "United Arab Emirates"],
  ["Abuja", "Nigeria"],
  ["Accra", "Ghana"],
  ["Addis Ababa", "Ethiopia"],
  ["Algiers", "Algeria"],
  ["Alofi", "Niue"],
  ["Amman", "Jordan"],
  ["Amsterdam", "Netherlands"],
  ["Andorra la Vella", "Andorra"],
  ["Ankara", "Turkey"],
  ["Antananarivo", "Madagascar"],
  ["Apia", "Samoa"],
  ["Ashgabat", "Turkmenistan"],
  ["Asmara", "Eritrea"],
  ["Astana", "Kazakhstan"],
  ["Asunción", "Paraguay"],
  ["Athens", "Greece"],
  ["Avarua", "Cook Islands"],
  ["Baghdad", "Iraq"],
  ["Baku", "Azerbaijan"],
  ["Bamako", "Mali"],
  ["Bandar Seri Begawan", "Brunei"],
  ["Bangkok", "Thailand"],
  ["Bangui", "Central African Republic"],
  ["Banjul", "Gambia"],
  ["Basseterre", "Saint Kitts and Nevis"],
  ["Beijing", "China"],
  ["Beirut", "Lebanon"],
  ["Belgrade", "Serbia"],
  ["Belmopan", "Belize"],
  ["Berlin", "Germany"],
  ["Bern", "Switzerland"],
  ["Bishkek", "Kyrgyzstan"],
  ["Bissau", "Guinea-Bissau"],
  ["Bogotá", "Colombia"],
  ["Brasília", "Brazil"],
  ["Bratislava", "Slovakia"],
  ["Brazzaville", "Republic of the Congo"],
  ["Bridgetown", "Barbados"],
  ["Brussels", "Belgium"],
  ["Bucharest", "Romania"],
  ["Budapest", "Hungary"],
  ["Buenos Aires", "Argentina"],
  ["Bujumbura", "Burundi"],
  ["Cairo", "Egypt"],
  ["Canberra", "Australia"],
  ["Caracas", "Venezuela"],
  ["Castries", "Saint Lucia"],
  ["Chisinau", "Moldova"],
  ["Conakry", "Guinea"],
  ["Copenhagen", "Denmark"],
  ["Dakar", "Senegal"],
  ["Damascus", "Syria"],
  ["Dhaka", "Bangladesh"],
  ["Dili", "East Timor"],
  ["Djibouti City", "Djibouti"],
  ["Dodoma", "Tanzania"],
  ["Doha", "Qatar"],
  ["Dublin", "Ireland"],
  ["Dushanbe", "Tajikistan"],
  ["Freetown", "Sierra Leone"],
  ["Funafuti", "Tuvalu"],
  ["Gaborone", "Botswana"],
  ["Georgetown", "Guyana"],
  ["Guatemala City", "Guatemala"],
  ["Hanoi", "Vietnam"],
  ["Harare", "Zimbabwe"],
  ["Havana", "Cuba"],
  ["Helsinki", "Finland"],
  ["Honiara", "Solomon Islands"],
  ["Islamabad", "Pakistan"],
  ["Jakarta", "Indonesia"],
  ["Jerusalem", "Israel"],
  ["Kabul", "Afghanistan"],
  ["Kampala", "Uganda"],
  ["Kathmandu", "Nepal"],
  ["Khartoum", "Sudan"],
  ["Kiev", "Ukraine"],
  ["Kigali", "Rwanda"],
  ["Kingston", "Jamaica"],
  ["Kingstown", "Saint Vincent and the Grenadines"],
  ["Kinshasa", "DR Congo"],
  ["Koror", "Palau"],
  ["Kuala Lumpur", "Malaysia"],
  ["Kuwait City", "Kuwait"],
  ["La Paz", "Bolivia"],
  ["Lagos", "Nigeria"],
  ["Libreville", "Gabon"],
  ["Lilongwe", "Malawi"],
  ["Lima", "Peru"],
  ["Lisbon", "Portugal"],
  ["Ljubljana", "Slovenia"],
  ["Lomé", "Togo"],
  ["London", "United Kingdom"],
  ["Luanda", "Angola"],
  ["Lusaka", "Zambia"],
  ["Luxembourg City", "Luxembourg"],
  ["Madrid", "Spain"],
  ["Majuro", "Marshall Islands"],
  ["Malabo", "Equatorial Guinea"],
  ["Malé", "Maldives"],
  ["Managua", "Nicaragua"],
  ["Manila", "Philippines"],
  ["Maputo", "Mozambique"],
  ["Maseru", "Lesotho"],
  ["Mbabane", "Eswatini"],
  ["Minsk", "Belarus"],
  ["Mogadishu", "Somalia"],
  ["Monrovia", "Liberia"],
  ["Montevideo", "Uruguay"],
  ["Moroni", "Comoros"],
  ["Moscow", "Russia"],
  ["Muscat", "Oman"],
  ["Nairobi", "Kenya"],
  ["Nassau", "Bahamas"],
  ["Naypyidaw", "Myanmar"],
  ["N'Djamena", "Chad"],
  ["New Delhi", "India"],
  ["Niamey", "Niger"],
  ["Nicosia", "Cyprus"],
  ["Nouakchott", "Mauritania"],
  ["Nouméa", "New Caledonia"],
  ["Nukuʻalofa", "Tonga"],
  ["Nur-Sultan", "Kazakhstan"],
  ["Nuku'alofa", "Tonga"],
  ["Oslo", "Norway"],
  ["Ottawa", "Canada"],
  ["Ouagadougou", "Burkina Faso"],
  ["Pago Pago", "American Samoa"],
  ["Palikir", "Micronesia"],
  ["Panama City", "Panama"],
  ["Paramaribo", "Suriname"],
  ["Paris", "France"],
  ["Phnom Penh", "Cambodia"],
  ["Port Louis", "Mauritius"],
  ["Port Moresby", "Papua New Guinea"],
  ["Port of Spain", "Trinidad and Tobago"],
  ["Port-au-Prince", "Haiti"],
  ["Port-Vila", "Vanuatu"],
  ["Porto-Novo", "Benin"],
  ["Prague", "Czech Republic"],
  ["Praia", "Cape Verde"],
  ["Pretoria", "South Africa"],
  ["Pristina", "Kosovo"],
  ["Pyongyang", "North Korea"],
  ["Quito", "Ecuador"],
  ["Rabat", "Morocco"],
  ["Reykjavik", "Iceland"],
  ["Riga", "Latvia"],
  ["Riyadh", "Saudi Arabia"],
  ["Rome", "Italy"],
  ["Roseau", "Dominica"],
  ["San José", "Costa Rica"],
  ["San Marino", "San Marino"],
  ["San Salvador", "El Salvador"],
  ["Sanaa", "Yemen"],
  ["Santiago", "Chile"],
  ["Santo Domingo", "Dominican Republic"],
  ["São Tomé", "São Tomé and Príncipe"],
  ["Sarajevo", "Bosnia and Herzegovina"],
  ["Seoul", "South Korea"],
  ["Singapore", "Singapore"],
  ["Skopje", "North Macedonia"],
  ["Sofia", "Bulgaria"],
  ["Sri Jayawardenepura Kotte", "Sri Lanka"],
  ["St. George's", "Grenada"],
  ["St. John's", "Antigua and Barbuda"],
  ["Stockholm", "Sweden"],
  ["Suva", "Fiji"],
  ["Taipei", "Taiwan"],
  ["Tallinn", "Estonia"],
  ["Tarawa", "Kiribati"],
  ["Tashkent", "Uzbekistan"],
  ["Tbilisi", "Georgia"],
  ["Tegucigalpa", "Honduras"],
  ["Tehran", "Iran"],
  ["Thimphu", "Bhutan"],
  ["Tirana", "Albania"],
  ["Tokyo", "Japan"],
  ["Tripoli", "Libya"],
  ["Tunis", "Tunisia"],
  ["Ulaanbaatar", "Mongolia"],
  ["Vaduz", "Liechtenstein"],
  ["Valletta", "Malta"],
  ["Vatican City", "Vatican City"],
  ["Victoria", "Seychelles"],
  ["Vienna", "Austria"],
  ["Vientiane", "Laos"],
  ["Vilnius", "Lithuania"],
  ["Warsaw", "Poland"],
  ["Washington, D.C.", "United States"],
  ["Wellington", "New Zealand"],
  ["Windhoek", "Namibia"],
  ["Yamoussoukro", "Ivory Coast"],
  ["Yaoundé", "Cameroon"],
  ["Yerevan", "Armenia"],
  ["Zagreb", "Croatia"],
];

// Deduplicate and sort alphabetically by city
export const CAPITALS: Capital[] = Array.from(
  new Map(RAW.map(([city, country]) => [city, { city, country, label: `${city}, ${country}` }])).values()
).sort((a, b) => a.city.localeCompare(b.city));

/** First 4 capitals shown before "See more" */
export const INITIAL_CAPITAL_COUNT = 4;
